name: Auto CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  cargo-test:
    name: Test - ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: moonrepo/setup-rust@v1
      - name: Cargo Test
        run: cargo test

  cargo-check:
    name: Check - ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: moonrepo/setup-rust@v1
      - name: Cargo Check
        run: cargo check

  cargo-clippy:
    name: Clippy - ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: moonrepo/setup-rust@v1
      - name: Install Clippy
        run: rustup component add clippy
      - name: Cargo Clippy
        run: cargo clippy

