name: IP-Hacker GUI Release Build

on:
#  push:
#    branches:
#      - "*"
#  pull_request:
#    branches:
#      - "*"
  workflow_dispatch:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Lib
        run: sudo apt update && sudo apt install -y musl-tools musl-dev musl libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build binary
        run: cargo build --profile minimal --jobs 32 --locked
        working-directory: ./gui
        env:
          CROSS_NO_WARNINGS: 0
      - name: Install Upx Binary
        run: sudo apt install -y upx
      - name: List Files
        run: ls -lah ./gui && ls -lah ./gui/target && ls -lah ./gui/target/minimal
      - name: Compress binary
        run: upx --brute ./gui/target/minimal/IP-Hacker-GUI
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64
          path: ./gui/target/minimal/IP-Hacker-GUI

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build binary
        run: cargo build --profile minimal --jobs 32 --locked
        working-directory: ./gui
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: ./gui/target/minimal/IP-Hacker-GUI.exe

  macos-amd64-release:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo Build
        run: cargo build --profile minimal
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64
          path: ./gui/target/minimal/IP-Hacker-GUI

  macos-arm64-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
      - name: Cargo Build
        run: cargo build --profile minimal
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: ./gui/target/minimal/IP-Hacker-GUI